const DELETE_FROM_CART = 'cart/DELETE_FROM_CART';
const INCREMENT_AMOUNT = 'cart/INCREMENT_AMOUNT';
const DECREMENT_AMOUNT = 'cart/DECREMENT_AMOUNT';
const ADD_TO_CART = 'cart/ADD_TO_CART';

export default {
  ADD_TO_CART,
  DELETE_FROM_CART,
  INCREMENT_AMOUNT,
  DECREMENT_AMOUNT,
};
