const CHANGE_FILTER = 'menu/CHANGE_FILTER';

const MENU_FETCH_REQUEST = 'menu/FETCH_REQUEST';
const MENU_FETCH_SUCCESS = 'menu/FETCH_SUCCESS';
const MENU_FETCH_ERROR = 'menu/FETCH_ERROR';

const CATEGORIES_FETCH_REQUEST = 'categories/FETCH_REQUEST';
const CATEGORIES_FETCH_SUCCESS = 'categories/FETCH_SUCCESS';
const CATEGORIES_FETCH_ERROR = 'categories/FETCH_ERROR';

const ADD_TO_CART = 'menu/ADD_TO_CART';

export default {
  ADD_TO_CART,
  CHANGE_FILTER,
  MENU_FETCH_REQUEST,
  MENU_FETCH_SUCCESS,
  MENU_FETCH_ERROR,
  CATEGORIES_FETCH_REQUEST,
  CATEGORIES_FETCH_SUCCESS,
  CATEGORIES_FETCH_ERROR,
};
